Repository Khan/jenkins-jobs, pull requests merged in 2025-04, with the labels that each got.

#312 [🔥AUDIT🔥] Fix the service-dir for fastly-vcl.
  jobs/deploy-fastly.groovy
Labels: audit, olc-4.0.628d3

#313 Decrypt stackdriver secrets for rollback.
  jobs/deploy-webapp.groovy
  jobs/emergency-rollback.groovy
Labels: olc-4.0.628d3

#314 [🔥AUDIT🔥] Alert to #whats-happening like we said we were going to, on fastly deploys.
  jobs/deploy-fastly.groovy
Labels: audit, olc-5.0.fb2b9

#316 Set 15 minute timeout for static build and deploy
  jobs/build-webapp.groovy
Labels: olc-5.0.fb2b9

#317 Run static build and deploy by itself
  jobs/build-webapp.groovy
Labels: olc-5.0.fb2b9

#320 [🔥AUDIT🔥] Rename districts_slack_secret to alertlib_slack_secret.
  vars/withSecrets.groovy
Labels: audit, olc-5.0.407da

#321 Update the graphql safelist when we deploy znds
  jobs/deploy-znd.groovy
Labels: olc-5.0.407da
